apiVersion: apps/v1
kind: Deployment
metadata:
  name: aura-api-gateway
  namespace: aura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: gcr.io/wc-2026-aura/api-gateway:latest
        ports:
        - containerPort: 8000
